variable "public_subnet_b_cidr"{}
variable "vpc_cidr"{}
variable "private_subnet_a_cidr"{}
variable "public_subnet_a_cidr"{}
variable "private_subnet_b_cidr"{}
variable "aws_access_key"{}
variable "aws_secret_key"{}
variable "aws_region"{}
variable "PUBLIC_KEY"{}